services:
  - type: web
    name: promedic
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "apache2-foreground"
    rootDir: .
    envVars:
      - key: APP_ENV
        value: production